title: Artem Davydov
logo: /assets/img/logo.png
description: Theoretical Astronomer| 4th Year UBC | Research Focus in Cosmology and Galactic Magnetism
google_analytics:278849089
theme: jekyll-theme-minimal
